### PR TITLE
Add xdebug package and set html_errors to On

### PR DESCRIPTION
**Pull request by bryantebeek**
Webgrind didn't work for me as expected because xdebug wasn't installed / enabled.

This should fix the errors. I'm not sure about setting html_errors = On in the php cookbook, might as well make our own template?

### CODE REVIEW

**Comment by ShawnMcCool** [comment]
Thanks!

**Comment by ShawnMcCool** [comment]
With this change, I'm getting this when running PHP

Failed loading /usr/lib/php5/20100525
value/xdebug.so:  /usr/lib/php5/20100525
value/xdebug.so: cannot open shared object file: No such file or directory

**Comment by ghost** [comment]
Yea, I noticed that also. It doesn't seem to break anything but it needs to be fixed of course. Not sure but without the first line of the xdebug.ini.erb it should work, seems it generates an url which could not be found later on.

**Comment by ghost** [comment]
ShawnMcCool, this error is fixed if I remove the first line of the xdebug.ini.erb. The one about the zend extension. The installation of php5-xdebug already takes care of linking the zend extension.

**Pull request merged**
